### ISSUE TITLE
Derailing trains

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [SEPR-EEP/taxe-game#13]
When a train finishes its journey (travelling on its last edge), but goes too fast (distance-travelled-per-turn > remaining-distance), this happens:
![image](https://cloud.githubusercontent.com/assets/621062/5793542/ef768892-9f3f-11e4-9445-12e9f66ef4f6.png)

**Comment by AlfioEmanueleFresta** [comment]
Fixed!
![image](https://cloud.githubusercontent.com/assets/621062/5793557/a527ea96-9f40-11e4-92d6-aeeedbc784e2.png)

**Comment by AlfioEmanueleFresta** [comment]
You can still derail a train if you get so many speed boster that your train travels more in a turn that the entire journey. #wontfix

**Comment by rc1035** [comment]
I'll look into it tomorrow, sounds like something I can fix in journey maybe
