### ISSUE TITLE
Opponent's name is not visible

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [SEPR-EEP/taxe-game#15]

**Comment by rc1035** [comment]
Links in with panel issue, if you resize window bigger it becomes visible

**Comment by AlfioEmanueleFresta** [comment]
Oh... I set the window to be non resizeable.

**Comment by AlfioEmanueleFresta** [comment]
@kokoff even after 43e8fdd6c528a364298c8682785154ac4fab1103 I see it like this:
![image](https://cloud.githubusercontent.com/assets/621062/5793828/95fc571e-9f4a-11e4-90cb-7b9972f787c9.png)

**Comment by kokoff** [comment]
I fixed the resizing problem with the panels however it would be best if we pick a specific size and stick to it.

**Comment by AlfioEmanueleFresta** [comment]
I think that we can stick to 1300x720.
