### ISSUE TITLE
Resource Paths

### ISSUE THREAD

**Issue by kokoff** [SEPR-EEP/taxe-game#16]
Resource paths don't work and non of the icons and images can be used in the GUI!

**Comment by AlfioEmanueleFresta** [comment]
`/resources/<file>`should do the trick - I can correctly see all of the files.

If you still have problems, in Eclipse go to  Project > Properties > Java Build Path > Source, expand "taxe-game/src", click "Excluded" and click edit. Make sure this list is empty.
