### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by rc1035** [SEPR-EEP/taxe-game#7]

**Comment by rc1035** [comment]
We need to further consider how to reward a player with points for completing a goal.

The variables we have are:

Shortest Number of Turns = Using shortest path between starting station and ending station - caclulated using Dijkstra's algorithm, this is the shortest number of turns it will take a train to complete a journey along this path - travelling constantly at its base speed (i.e. assumes train had no modifiers used on it).

Actual Number of Turns = The actual number of turns it takes for a player to travel along their chosen journey between the starting station and ending station. This will depend upon whether the player chooses an optimal path and whether any modifiers are used to change the train's actual speed during the journey.


Our requirment doc states this is how we should calculate score:
Score = Goal difficulty coefficient / Number of turns to complete goal 

So maybe we could have:
Difficulty coefficient = Shortest Number of Turns * 100
Score = Difficulty coefficient / Actual Number of Turns

For example, a goal with 5 shortest number of turns, if completed in 6 turns would reward 83 points. If completed in 3 turns (e.g. a speed booster was used) would reward 166 points.

Thoughts?

**Comment by rc1035** [comment]
Also, I'm still working on testing the goal class. Should have it finished tomorrow morning.

**Comment by AlfioEmanueleFresta** [comment]
@rc1035 Great, I like that. I see you assigned me to this issue - do you want me to complete the functions to calculate the score?

**Comment by rc1035** [comment]
Oops I had just done that to send a notification, I'll switch it back to me. We can always easily change the score calculation if we find something else works better.

**Comment by rc1035** [comment]
I've changed the formula as the previous one would award the same score for a short journey as a long one - which is obviously not fair.

At the moment it is:

Score = Total length of journey * (Shortest number of turns / Actual number of turns)

I'll do further testing for this later, I may tweak it a bit.

**Comment by rc1035** [comment]
Absolute goals are now working. Score has not been implemented as it is not part of assessment 2.

Each turn a player will recieve a randomly generated goal (a random starting station and random ending station - where start station != end station). Upon a goal being completed a new goal will replace it with a starting station which is the ending station of the previous goal.
